### ISSUE TITLE
[1.2.3] 상속을 통한 확장의 단점

### ISSUE THREAD

**Issue by gmelon** [SSAFY11th-book-study/book-study#1]
p.72 ~ p.73에서 상속을 통한 기능 확장의 단점에 대해 말하고 있습니다.
책에서는 단순히 `상속을 통한 상하위 클래스의 관계는 생각보다 밀접하다` 라고 이야기하고 넘어갔는데 구체적으로는 어떤 경우들이 있을지 궁금합니다!

제가 지금 생각했을 때 떠오르는 걸로는 아래와 같은 부모 클래스가 있고,
### 부모 클래스
```java
public class Parent {
    protected List<String> list = new ArrayList<>();
}
```

아래와 같은 자식 클래스에서 부모의 멤버를 사용해서 무언가를 하고 있다고 했을 때
### 자식 클래스
```java
public class Child extends Parent {
    public void doSomething() {
        list.add("블라블라");
    }
}
```

자식 클래스가 부모의 내부 구현에 의존하게 되는 상황이 되어 아래와 같이 부모 클래스가 변경되면 자식 클래스가 깨질 수 있다는 생각이 들었습니다.
```java
public class Parent {
    protected String[] list = new String[10];
}
```

추가적으로, 개발을 하시며 상속을 통한 확장으로 인한 문제를 경험한 적이 있으시다면 공유해주시면 많은 공부가 될 것 같습니다 :)

**Comment by limjongheok** [comment]
제가 생각하기에는 상속을 통한 확장 문제로는 부모 클래스에 새로운 기능이 추가 될시 문제가 될 수 있다 생각합니다
```
public class Duck{
    public void swim(){
      System.out.println("수영 중");
    }
}

class ThunderDuck extends Duck{ //...}

```
