### ISSUE TITLE
[1.2.3] 템플릿 메소드 패턴 vs 팩토리 메소드 패턴

### ISSUE THREAD

**Issue by hj-k66** [SSAFY11th-book-study/book-study#2]
71p ~ 72p 에서 `DB 커넥션 기능을 UserDao에 팩토리 메소드 패턴을 적용해 getConnection()을 분리`하면서 템플릿 메소드 패턴과 팩토리 메소드 패턴을 둘 다 언급했습니다.  이 두 패턴의 차이점이 궁금합니다!

또, `템플릿 메소드 패턴은 스프링에서 애용되는 디자인패턴` 이라 언급되어 있는데, 실제 스프링 내부코드 중 어떤 부분이 템플릿 메소드 패턴이 적용된 건지 예시를 찾아보면 좋을 것 같습니다.

**Comment by limjongheok** [comment]
우선 템플릿 메소드 패턴 정리한게 있어서 올립니다.
https://velog.io/@limjongheok/%ED%85%9C%ED%94%8C%EB%A6%BF-%EB%A9%94%EC%86%8C%EB%93%9C-%ED%8C%A8%ED%84%B4

**Comment by gmelon** [comment]
첫번째 질문에 대해서는
템플릿 메서드 패턴이 오브젝트를 생성하여 반환하는 역할을 수행한다면, 팩토리 메서드 패턴으로도 볼 수 있다 정도로 저는 이해했습니다. 다른 분들은 어떻게 생각하시는지 궁금하네요!

스프링에서 템플릿 메서드 패턴이 사용된 예시는 https://steady-coding.tistory.com/585#Spring%EC%97%90%EC%84%9C_%ED%85%9C%ED%94%8C%EB%A6%BF_%EB%A9%94%EC%86%8C%EB%93%9C_%ED%8C%A8%ED%84%B4%EC%9D%84_%EC%A0%81%EC%9A%A9%ED%95%9C_%EC%82%AC%EB%A1%80 이 글을 보면 좋을 것 같아요!
