### ISSUE TITLE
[3.5] 템플릿 메서드 패턴 vs 전략 패턴 vs 템플릿 콜백 패턴

### ISSUE THREAD

**Issue by gmelon** [SSAFY11th-book-study/book-study#32]
3장에서 계속해서 언급되는 아래 3가지 디자인 패턴들이 닮아있으면서도 조금씩 다른 점이 있는 것 같습니다.

* 템플릿 메서드 패턴
* 전략 패턴
* 템플릿 콜백 패턴

명확하게 정리하고 넘어가면 좋을 것 같아서 이슈 남깁니다. 저도 찾아보고 댓글 달아두겠습니다!

**Comment by sootudio** [comment]
유명한 사이트라서 다들 이미 보셨을 수도 있지만... 여기만큼 설명이 맛도리인 곳이 없어서 참고 사이트로 남깁니다.

> 템플릿 메서드 패턴 - https://refactoring.guru/ko/design-patterns/template-method

> 전략 패턴 - https://refactoring.guru/ko/design-patterns/strategy

템플릿 콜백 패턴은 GOF 패턴이 아니라서 그런지, 위 사이트에 설명이 없어 괜찮은 설명이 있는 블로그를 찾아왔습니다.

> 템플릿 콜백 패턴 - https://inpa.tistory.com/entry/GOF-%F0%9F%92%A0-Template-Callback-%EB%B3%80%ED%98%95-%ED%8C%A8%ED%84%B4-%EC%95%8C%EC%95%84%EB%B3%B4%EA%B8%B0

위에 있는 사이트들에 아주 정리가 잘 되어 있지만... 저도 나름대로 정리를 해 보자면

=====작성중...=====

**Comment by gmelon** [comment]
한줄 정리 + 장단점 + 차이점 정리하기
