### ISSUE TITLE
[4.1.4] 예외 전환과 예외 포장

### ISSUE THREAD

**Issue by a-young-kim** [SSAFY11th-book-study/book-study#39]
![image](https://github.com/SSAFY11th-book-study/book-study/assets/76930260/cb6bffd1-b839-4b26-8fb6-634f89f889bc)

![image](https://github.com/SSAFY11th-book-study/book-study/assets/76930260/218b01bb-e8c9-4aee-8aa3-0e266cf7f910)

첫번쨰 이미지의 예외 전환 부분은 예외 포장이라고도 할 수 있는지 궁금합니다.

**Comment by gmelon** [comment]
저는 예외 포장의 하위에 예외 전환이라는 개념이 존재한다고 생각합니다.

위의 두 예제 모두 예외를 다른 예외로 감싸는 '예외 포장' 이지만, 첫번째 예제의 경우 예외를 감싸면서 의미를 더 명확하게 표현할 수 있는 다른 예외로 감싸기 때문에 동일하게 '포장'이긴 하지만, 조금 더 구체적으로는 '예외 전환'이다 라고 이해했습니다.

**Comment by a-young-kim** [comment]
예외 포장의 하위에 예외 전환이라는 개념이 존재
예외를 포장하며 좀 더 구체적으로 결과를 리턴할 수 있으면 예외 전환이라고 한다.
