### ISSUE TITLE
[4.1.4] unchecked exception의 throws 선언

### ISSUE THREAD

**Issue by gmelon** [SSAFY11th-book-study/book-study#40]
4.1 절에서 최근에는 런타임 예외의 사용이 보편화되고 있다고 합니다. checked/unchecked 관련해서 평소에 많이 궁금했던 내용이었는데 한방에 납득이 됐습니다. 그러면서 추가로, 런타임 예외는 unchecked 이므로 throws 해줄 필요가 없지만 클라이언트 개발자에게 해당 예외의 발생 가능성을 알리고, 처리가 필요하면 하라는 것을 표현한다고 합니다.

<img width="697" alt="image" src="https://github.com/SSAFY11th-book-study/book-study/assets/33623106/b3b56a37-6a1d-40e5-92d9-318cccca43d5">

그런데 제 개인적인 경험으로는 단지 throws에 예외가 선언되어 있는 것만으로는 해당 예외를 처리해야겠다고 생각하기가 쉽지 않던데, throws 외에 런타임 예외의 처리를 강조하거나 명시해둘 방법이 있는지 궁금합니다.

**Comment by sootudio** [comment]
제가 찾아봤을 때는 javadoc 주석을 사용하여 메소드에서 발생하는 예외를 문서화하는 방법이 있다고 합니다.

[https://www.oracle.com/kr/technical-resources/articles/java/javadoc-tool.html#throwstag](https://www.oracle.com/kr/technical-resources/articles/java/javadoc-tool.html#throwstag)

오라클 공식 문서에 보면, javadoc 주석에 @throws 태그를 사용하여 예외를 문서화하는 방법과 관련된 가이드가 나옵니다.

내용을 간단히 정리해 보면.

1. @throws 태그를 사용한 예외 문서화: Java의 API 명세서는 호출자와 구현자 간의 계약입니다. API를 생성할 때 예외 처리에 대한 계약을 명시하는 방법에 대한 설명입니다. 이는 메소드 선언에서 throws 절과 javadoc에서의 @throws 태그 두 가지 방법으로 표현됩니다.

2. @throws 태그의 목적: @throws 태그는 프로그래머가 반드시 처리해야 할 (checked exceptions의 경우) 또는 처리하고 싶을 수 있는 (unchecked exceptions의 경우) 예외를 나타냅니다.

3. 문서화해야 할 예외: @throws 태그를 사용하여 다음과 같은 예외를 문서화합니다.

    - 모든 checked exceptions

    - 호출자가 합리적으로 catch하고자 할 수 있는 unchecked exceptions

5. Unchecked 예외 문서화: 메소드가 던질 수 있는 unchecked 예외를 문서화하는 것이 일반적으로 바람직합니다. 이는 호출자가 이러한 예외를 처리할 수 있도록 하기 위함입니다.

6. Checked와 Unchecked 예외: RuntimeException, Error 및 그 서브클래스는 unchecked exceptions입니다. 나머지 모든 예외 서브클래스는 checked exceptions입니다.

7. Throws 절에 대한 배경: Checked 예외는 메소드의 throws 절에 포함되어야 합니다. 이는 컴파일러가 어떤 예외를 검사할지 알 수 있도록 하기 위함입니다.

8. Throws 절과 Unchecked 예외: By convention, unchecked exceptions는 throws 절에 포함되지 않아야 합니다. 그러나 예외가 RuntimeException인 경우에도 throws 절에 포함되는 경우가 있습니다. 이는 올바른 예외 처리 방법을 명시하기 위함입니다.
