### ISSUE TITLE
[1.6] bean 및 싱글톤 레지스터리  

### ISSUE THREAD

**Issue by limjongheok** [SSAFY11th-book-study/book-study#6]
책에서는 
![image](https://github.com/SSAFY11th-book-study/book-study/assets/42922673/2a0de1f3-8f6c-4e4f-baa1-665055ca0ced)
client 가 ApplicationContext 에 getBean을 통해 요청을 하면 ApllicationContext는 받은 @Configuration 속 Bean 목록에서 적절한 bean을 찾아 생성하고 싶은 객체를 생성 하여 사용하는 방식이라 설명하고 있습니다.  
그리고 밑에서 bean은 싱글톤 레지스트리라 하여 하나의 인스턴스만 갖을수 있다라고 설명하고 있습니다.
제 생각에는  getBean  요청시 빈 bean 속에 인스턴스를 생성하는 방식인 lazy 스러운 방식이라 생각하는데 
그렇다면 멀티스레드 환경에서 
(스레드1 getBean(UserDao)) -> (스레드 2 getBean(UserDao)) -> (스레드 1 bean 속 userDao 생성 후 반환) -> (스레드 2 bean속 UserDao 생성 후 반환) 이런 식으로 인스턴스가 여러개가 생기는 문제가 발생할 수 있다 생각하는데 그렇다면 이러한 멀티쓰레드 환경 문제는 spring Bean은 어떻게 해결하는지 궁금합니다. 
혹은 이렇게 Bean 자체를 싱글톤으로 보면 안돼나요??

**Comment by gmelon** [comment]
BeanFactory의 추상 클래스인 AbstractBeanFactory에 정의된 `getBean()` 메서드는 아래와 같이 같은 클래스의 `doGetBean()`을 호출하고,
<img width="638" alt="image" src="https://github.com/SSAFY11th-book-study/book-study/assets/33623106/6df68917-dd20-4fef-8ca1-c2371fb17139">

`doGetBean()` 은 다시 DefaultSingletonBeanRegistry 클래스의 `getSingleton()`을 호출합니다.
<img width="858" alt="image" src="https://github.com/SSAFY11th-book-study/book-study/assets/33623106/66e4972e-b4c2-4c3c-b558-e46299bd490e">

그리고 `getSingleton()` 메서드는 해당 빈이 있으면 반환하고 없으면 생성 후 반환하는데
아래와 같이 synchronized 키워드로 동기화되어 있는 것을 확인할 수 있습니다.
<img width="806" alt="image" src="https://github.com/SSAFY11th-book-study/book-study/assets/33623106/cd6fd141-c7c0-4dd1-9f5b-293f872ce9b7">

그래서 아마도 이러한 방식으로 멀티쓰레드에서의 지연 초기화 문제를 해결하고 있지 않나 생각했습니다.

**Comment by sootudio** [comment]
위에 있는 답변과 똑같은 내용이지만...

스프링 프레임워크에서 getSingleton() 메서드는 싱글톤 빈의 생성과 관리를 위해 내부적으로 'DefaultSingletonBeanRegistry' 클래스 에 의해 사용되고, 해당 클래스는 여러 스레드가 동시에 동일한 빈을  요청할 경우, 단일한 인스턴스만을 생성하고 반환하는 메커니즘을 가지고 있다고 합니다.

질문에 올렸던 여러 개의 스레드에서 동시에 getBean()을 호출하는 과정을 단계별로 정리해보니

**1. 스레드1이 getBean("userDao")를 호출**
- ApplicationContext가 getSingleton() 메서드를 호출하여 userDao 인스턴스가 존재하는지 확인함.
- userDao 인스턴스가 아직 생성되지 않았으므로, 스프링은 synchronized 블록 내에서 빈을 생성

**2. 스레드2가 getBean("userDao")를 호출**
- 스레드2 가 getSingleton()을 호출함.
- synchronized 블록이 이미 스레드1에 의해 진입 중이므로, 스레드2는 블록 외부에서 대기

**3. 스레드1이 userDao 생성을 완료하고 반환**
- 스레드1은 userDao의 인스턴스를 성공적으로 생성하고, 이를 싱글톤 캐시에 저장
- 이후 synchronized 블록을 빠져나오며, 생성된 userDao 인스턴스를 스레드1에 반환

**4. 스레드2가 getSingleton()을 진행**
- 스레드1이 synchronized 블록을 빠져나오면, 스레드2는 이제 synchronized 블록에 진입
- 스레드2는 싱글톤 캐시를 검사하고, (스레드 1에 의해)이미 생성된 userDao 인스턴스를 발견
- 스레드2에게도 동일한 userDao 인스턴스가 반환


이런 과정으로 Spring bean에서 멀티스레스 상황에 여러개의 인스턴스가 생길 수 있는 문제를 해결한다고 이해했습니다.

**Comment by hj-k66** [comment]
저는 getBean 요청 시 빈이 생성되는 lazy 방식이 아닌, ApplicationContext에 빈을 등록할 때 생성되고 getBean 요청 시에는 빈이 조회되는 것이라고 이해했습니다.

```java
@Configuration
public class DaoFactory {

    @Bean
    public UserDao userDao(){
        System.out.println("call userDao()");
        UserDao userDao = new UserDao(connectionMaker());
        return userDao;
    }

    @Bean
    public AccountDao accountDao(){
         System.out.println("call accountDao()");
        AccountDao accountDao = new AccountDao(connectionMaker());
        return accountDao;
    }

    @Bean
    public ConnectionMaker connectionMaker(){
        System.out.println("call connectionMaker()");
        return new DConnectionMaker();
    }
}
```
다음과 같은 DaoFactory클래스가 있습니다. 각 Bean 메소드를 호출할 시 print되게 하였습니다.

```java
public class DaoFactoryTest {

    @Test
    @DisplayName("call Bean Test")
    void createObjectByBean(){
        ApplicationContext applicationContext = new AnnotationConfigApplicationContext(DaoFactory.class);
        UserDao userDao1 = applicationContext.getBean("userDao", UserDao.class);
        AccountDao account= applicationContext.getBean("accountDao", AccountDao.class);
        ConnectionMaker  c = applicationContext.getBean("connectionMaker", ConnectionMaker .class);
        
    }

}
```
다음과 같은 테스트 코드를 실행했을 때, 만약 getBean() 시 오브젝트가 생성되는 것이면,  userDao 1회, account 1회, userDao와 accountDao와 연관관계가 있는 connectionMaker 3회 호출 될 것이라 생각되지만, 실제로는 다음과 같은 결과를 얻습니다.
```
call userDao()
call accountDao()
call connectionMaker()
```
또, getBean부분을 주석처리하고 `ApplicationContext applicationContext = new AnnotationConfigApplicationContext(DaoFactory.class);` 만 실행했을 때 동일한 결과를 얻을 수 있었습니다.

그래서 저는 ApplicationContext에 등록 시에만 인스턴스를 생성하고 getBean 시에는 생성된 인스턴스의 레퍼런스를 전달하는 것이라 생각합니다.

**Comment by a-young-kim** [comment]
저도 처음에는 getBean 메소드를 호출하면 그 때 인스턴스를 생성하는 것이라고 생각했는데 희정님이 말씀하신 것이 맞는 것 같습니다. 
 ApplicationContext를 통해 스프링 컨테이너가 생성되고 스프링 컨테이너가 @Bean이라고 붙은 메소드를 모두 호출하여 생성 후 반환하는 것으로 이해했습니다. 
그리고 getBean() 메소드는 스프링 컨테이너에 존재하는 스프링 빈을 찾아 객체를 반환하는 역할을 하는 것으로 이해하였습니다. 

참고 링크
https://velog.io/@kureungkureung/Spring-Bean
