### ISSUE TITLE
[1.6.1] 서버 환경에서의 싱글톤

### ISSUE THREAD

**Issue by gmelon** [SSAFY11th-book-study/book-study#8]
p.110에 보면 `여러 개의 JVM에 분산돼서 설치가 되는 경우에도 각각 독립적으로 오브젝트가 생기기 때문에 싱글톤으로서의 가치가 떨어진다` 라고 되어 있습니다.

그런데 생각해보니 사실 이러한 단점은 스프링에서 싱글톤으로 관리해주는 애플리케이션 컨텍스트를 사용해도 마찬가지로 발생하는 것이 아닌가? 하는 생각이 들었습니다. 제가 맞게 이해한 것일까요?! 어떻게 생각하시는지 궁금합니다.

**Comment by sootudio** [comment]
제가 찾아봤을 때는, 스프링의 싱글톤 빈 역시 분산된 환경에서는 각각의 싱글톤 빈 인스턴스가 생성된다고 나와 있었습니다. 

해결 방법으로는 
- 각 JVM 간에 데이터를 공유하고 동일한 싱글톤 객체에 접근할 수 있는 분산 캐시
- 여러 노드에서의 싱글톤 객체에  대한 동시 접근을 제어할 수 있는 분산락 
등이 있다고 합니다. (두 가지 개념을 정확히 이해한건진 모르겠습니다 ㅠㅠ)

다만 위의 방법들은 스프링 싱글톤 빈을 사용하는 상황에만 적용되는 것이 아니고, 싱글톤 패턴을 사용하는 상황에도 적용할 수 있기 때문에 문제 상황에 대한 스프링 싱글톤 빈만의 해결법은 아니라고 이해했습니다.

결론적으로,  '여러 개의 JVM에 분산돼서 설치가 되는 경우에도 각각 독립적으로 오브젝트가 생기기 때문에 싱글톤으로서의 가치가 떨어진다'는 문제는 싱글톤 패턴뿐만 아니라 스프링의 싱글톤 빈에도 적용될 수 있다고 생각합니다. 책에서 해당 문제를 왜 싱글톤 패턴만의 문제인 것처럼 적어 놓았는지는 저도 잘 모르겠습니다...
